server:
  port: 10010

spring:
  application:
    name: test-ai-backend
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testai?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 123456

file:
  upload-path: ${user.dir}/data/documents
skill:
  testcase-gen:
    path: classpath:skills/testcase-gen.skill

ai:
  batch:
    enable: false
    max-tokens: 2048

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.testai.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

logging:
  level:
    com.testai.mapper: debug
